using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using backend.DTOs;
using backend.Models;
using backend.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace backend.Controllers;

[ApiController]
[Route("api/document-hub")]
[Authorize]
public class DocumentHubController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly IAuthService _authService;
    private readonly IDocumentAiService _documentAiService;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IConfiguration _configuration;

    public DocumentHubController(
        ApplicationDbContext context,
        IAuthService authService,
        IDocumentAiService documentAiService,
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration)
    {
        _context = context;
        _authService = authService;
        _documentAiService = documentAiService;
        _httpClientFactory = httpClientFactory;
        _configuration = configuration;
    }

    [HttpGet("label-sets")]
    public async Task<ActionResult<List<DocumentLabelSetDto>>> GetLabelSets()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentLabelSets
            .AsNoTracking()
            .Include(x => x.ClassificationLabels)
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapLabelSet).ToList());
    }

    [HttpPost("label-sets")]
    public async Task<ActionResult<DocumentLabelSetDto>> CreateLabelSet([FromBody] CreateDocumentLabelSetRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.LabelSetName))
        {
            return BadRequest(new { message = "Label set name is required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentLabelSet
        {
            LabelSetName = request.LabelSetName.Trim(),
            LabelSetDescription = request.LabelSetDescription?.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentLabelSets.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapLabelSet(entity));
    }

    [HttpPut("label-sets/{labelSetId:int}")]
    public async Task<ActionResult<DocumentLabelSetDto>> UpdateLabelSet(int labelSetId, [FromBody] UpdateDocumentLabelSetRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentLabelSets
            .Include(x => x.ClassificationLabels)
            .FirstOrDefaultAsync(x => x.DocumentLabelSetId == labelSetId);
        if (entity == null)
        {
            return NotFound(new { message = "Label set not found." });
        }

        if (request.LabelSetName != null)
        {
            var normalizedName = request.LabelSetName.Trim();
            if (string.IsNullOrWhiteSpace(normalizedName))
            {
                return BadRequest(new { message = "Label set name cannot be empty." });
            }
            entity.LabelSetName = normalizedName;
        }

        if (request.LabelSetDescription != null)
        {
            entity.LabelSetDescription = request.LabelSetDescription.Trim();
        }

        if (request.IsActive.HasValue)
        {
            entity.IsActive = request.IsActive.Value;
        }

        if (request.Labels != null)
        {
            var replacementLabels = request.Labels
                .Where(x => !string.IsNullOrWhiteSpace(x.ClassificationLabel) && !string.IsNullOrWhiteSpace(x.ClassificationPrompt))
                .Select(x => new DocumentClassificationLabel
                {
                    DocumentLabelSetId = labelSetId,
                    ClassificationLabel = x.ClassificationLabel.Trim(),
                    ClassificationDescription = x.ClassificationDescription?.Trim(),
                    ClassificationPrompt = x.ClassificationPrompt.Trim(),
                    SeedDocumentName = x.SeedDocumentName?.Trim(),
                    SeedDocumentHash = x.SeedDocumentHash?.Trim(),
                    IsAutoGenerated = x.IsAutoGenerated,
                    IsActive = x.IsActive,
                    CreatedByUserId = GetCurrentUserId(),
                    CreatedDate = DateTime.UtcNow
                })
                .ToList();

            _context.DocumentClassificationLabels.RemoveRange(entity.ClassificationLabels);
            entity.ClassificationLabels = replacementLabels;
        }

        entity.UpdatedByUserId = GetCurrentUserId();
        entity.UpdatedDate = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        var reloaded = await _context.DocumentLabelSets
            .AsNoTracking()
            .Include(x => x.ClassificationLabels)
            .FirstOrDefaultAsync(x => x.DocumentLabelSetId == labelSetId);
        if (reloaded == null) return NotFound(new { message = "Label set not found after update." });

        return Ok(MapLabelSet(reloaded));
    }

    [HttpDelete("label-sets/{labelSetId:int}")]
    public async Task<ActionResult> DeleteLabelSet(int labelSetId)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentLabelSets
            .Include(x => x.ClassificationLabels)
            .FirstOrDefaultAsync(x => x.DocumentLabelSetId == labelSetId);
        if (entity == null)
        {
            return NotFound(new { message = "Label set not found." });
        }

        if (entity.ClassificationLabels.Count > 0)
        {
            _context.DocumentClassificationLabels.RemoveRange(entity.ClassificationLabels);
        }
        _context.DocumentLabelSets.Remove(entity);
        await _context.SaveChangesAsync();

        return NoContent();
    }

    [HttpPost("label-sets/{labelSetId:int}/labels")]
    public async Task<ActionResult<DocumentClassificationLabelDto>> CreateClassificationLabel(int labelSetId, [FromBody] CreateDocumentClassificationLabelRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.ClassificationLabel) || string.IsNullOrWhiteSpace(request.ClassificationPrompt))
        {
            return BadRequest(new { message = "Classification label and prompt are required." });
        }

        var labelSet = await _context.DocumentLabelSets.FirstOrDefaultAsync(x => x.DocumentLabelSetId == labelSetId);
        if (labelSet == null) return NotFound(new { message = "Label set not found." });

        var userId = GetCurrentUserId();
        var entity = new DocumentClassificationLabel
        {
            DocumentLabelSetId = labelSetId,
            ClassificationLabel = request.ClassificationLabel.Trim(),
            ClassificationDescription = request.ClassificationDescription?.Trim(),
            ClassificationPrompt = request.ClassificationPrompt.Trim(),
            SeedDocumentName = request.SeedDocumentName?.Trim(),
            SeedDocumentHash = request.SeedDocumentHash?.Trim(),
            IsAutoGenerated = request.IsAutoGenerated,
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentClassificationLabels.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapClassificationLabel(entity));
    }

    [HttpGet("summarisation-templates")]
    public async Task<ActionResult<List<DocumentSummarisationTemplateDto>>> GetSummarisationTemplates()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentSummarisationTemplates
            .AsNoTracking()
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapSummarisationTemplate).ToList());
    }

    [HttpPost("summarisation-templates")]
    public async Task<ActionResult<DocumentSummarisationTemplateDto>> CreateSummarisationTemplate([FromBody] CreateDocumentSummarisationTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.SummarisationName) || string.IsNullOrWhiteSpace(request.SummarisationPrompt))
        {
            return BadRequest(new { message = "Summarisation name and prompt are required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentSummarisationTemplate
        {
            SummarisationName = request.SummarisationName.Trim(),
            SummarisationDescription = request.SummarisationDescription?.Trim(),
            SummarisationPrompt = request.SummarisationPrompt.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentSummarisationTemplates.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapSummarisationTemplate(entity));
    }

    [HttpPut("summarisation-templates/{templateId:int}")]
    public async Task<ActionResult<DocumentSummarisationTemplateDto>> UpdateSummarisationTemplate(int templateId, [FromBody] UpdateDocumentSummarisationTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentSummarisationTemplates.FirstOrDefaultAsync(x => x.DocumentSummarisationTemplateId == templateId);
        if (entity == null)
        {
            return NotFound(new { message = "Summarisation template not found." });
        }

        if (request.SummarisationName != null)
        {
            entity.SummarisationName = request.SummarisationName.Trim();
        }

        if (request.SummarisationDescription != null)
        {
            entity.SummarisationDescription = request.SummarisationDescription.Trim();
        }

        if (request.SummarisationPrompt != null)
        {
            entity.SummarisationPrompt = request.SummarisationPrompt.Trim();
        }

        if (request.IsActive.HasValue)
        {
            entity.IsActive = request.IsActive.Value;
        }

        entity.UpdatedByUserId = GetCurrentUserId();
        entity.UpdatedDate = DateTime.UtcNow;

        await _context.SaveChangesAsync();
        return Ok(MapSummarisationTemplate(entity));
    }

    [HttpDelete("summarisation-templates/{templateId:int}")]
    public async Task<ActionResult> DeleteSummarisationTemplate(int templateId)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentSummarisationTemplates.FirstOrDefaultAsync(x => x.DocumentSummarisationTemplateId == templateId);
        if (entity == null)
        {
            return NotFound(new { message = "Summarisation template not found." });
        }

        _context.DocumentSummarisationTemplates.Remove(entity);
        await _context.SaveChangesAsync();
        return NoContent();
    }

    [HttpGet("extraction-templates")]
    public async Task<ActionResult<List<DocumentExtractionTemplateDto>>> GetExtractionTemplates()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentExtractionTemplates
            .AsNoTracking()
            .Include(x => x.ExtractionFields)
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapExtractionTemplate).ToList());
    }

    [HttpPost("extraction-templates")]
    public async Task<ActionResult<DocumentExtractionTemplateDto>> CreateExtractionTemplate([FromBody] CreateDocumentExtractionTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.ExtractionTemplateName))
        {
            return BadRequest(new { message = "Extraction template name is required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentExtractionTemplate
        {
            ExtractionTemplateName = request.ExtractionTemplateName.Trim(),
            ExtractionTemplateDescription = request.ExtractionTemplateDescription?.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentExtractionTemplates.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapExtractionTemplate(entity));
    }

    [HttpPut("extraction-templates/{templateId:int}")]
    public async Task<ActionResult<DocumentExtractionTemplateDto>> UpdateExtractionTemplate(
        int templateId,
        [FromBody] UpdateDocumentExtractionTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentExtractionTemplates
            .Include(x => x.ExtractionFields)
            .FirstOrDefaultAsync(x => x.DocumentExtractionTemplateId == templateId);
        if (entity == null)
        {
            return NotFound(new { message = "Extraction template not found." });
        }

        if (request.ExtractionTemplateName != null)
        {
            var normalizedName = request.ExtractionTemplateName.Trim();
            if (string.IsNullOrWhiteSpace(normalizedName))
            {
                return BadRequest(new { message = "Extraction template name cannot be empty." });
            }
            entity.ExtractionTemplateName = normalizedName;
        }

        if (request.ExtractionTemplateDescription != null)
        {
            entity.ExtractionTemplateDescription = request.ExtractionTemplateDescription.Trim();
        }

        if (request.IsActive.HasValue)
        {
            entity.IsActive = request.IsActive.Value;
        }

        if (request.Fields != null)
        {
            var replacementFields = request.Fields
                .Where(x => !string.IsNullOrWhiteSpace(x.FieldName))
                .Select(x => new DocumentExtractionField
                {
                    DocumentExtractionTemplateId = templateId,
                    FieldName = x.FieldName.Trim(),
                    ExampleValue = x.ExampleValue?.Trim(),
                    AnchorTextBefore = x.AnchorTextBefore?.Trim(),
                    AnchorTextAfter = x.AnchorTextAfter?.Trim(),
                    FieldExtractionPrompt = x.FieldExtractionPrompt?.Trim(),
                    PageNumber = x.PageNumber,
                    BoundingBoxJson = x.BoundingBoxJson,
                    IsActive = x.IsActive,
                    CreatedByUserId = GetCurrentUserId(),
                    CreatedDate = DateTime.UtcNow
                })
                .ToList();

            _context.DocumentExtractionFields.RemoveRange(entity.ExtractionFields);
            entity.ExtractionFields = replacementFields;
        }

        entity.UpdatedByUserId = GetCurrentUserId();
        entity.UpdatedDate = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        var reloaded = await _context.DocumentExtractionTemplates
            .AsNoTracking()
            .Include(x => x.ExtractionFields)
            .FirstOrDefaultAsync(x => x.DocumentExtractionTemplateId == templateId);
        if (reloaded == null) return NotFound(new { message = "Extraction template not found after update." });

        return Ok(MapExtractionTemplate(reloaded));
    }

    [HttpDelete("extraction-templates/{templateId:int}")]
    public async Task<ActionResult> DeleteExtractionTemplate(int templateId)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentExtractionTemplates
            .Include(x => x.ExtractionFields)
            .FirstOrDefaultAsync(x => x.DocumentExtractionTemplateId == templateId);
        if (entity == null)
        {
            return NotFound(new { message = "Extraction template not found." });
        }

        if (entity.ExtractionFields.Count > 0)
        {
            _context.DocumentExtractionFields.RemoveRange(entity.ExtractionFields);
        }
        _context.DocumentExtractionTemplates.Remove(entity);
        await _context.SaveChangesAsync();

        return NoContent();
    }

    [HttpPost("extraction-templates/{templateId:int}/fields")]
    public async Task<ActionResult<DocumentExtractionFieldDto>> CreateExtractionField(int templateId, [FromBody] CreateDocumentExtractionFieldRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.FieldName))
        {
            return BadRequest(new { message = "Field name is required." });
        }

        var template = await _context.DocumentExtractionTemplates.FirstOrDefaultAsync(x => x.DocumentExtractionTemplateId == templateId);
        if (template == null) return NotFound(new { message = "Extraction template not found." });

        var userId = GetCurrentUserId();
        var entity = new DocumentExtractionField
        {
            DocumentExtractionTemplateId = templateId,
            FieldName = request.FieldName.Trim(),
            ExampleValue = request.ExampleValue?.Trim(),
            AnchorTextBefore = request.AnchorTextBefore?.Trim(),
            AnchorTextAfter = request.AnchorTextAfter?.Trim(),
            FieldExtractionPrompt = request.FieldExtractionPrompt?.Trim(),
            PageNumber = request.PageNumber,
            BoundingBoxJson = request.BoundingBoxJson,
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentExtractionFields.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapExtractionField(entity));
    }

    [HttpPost("correction-feedback")]
    public async Task<ActionResult> CreateCorrectionFeedback([FromBody] CreateDocumentCorrectionFeedbackRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (request.DocumentProcessingRunId <= 0 || string.IsNullOrWhiteSpace(request.ProcessingType))
        {
            return BadRequest(new { message = "DocumentProcessingRunId and ProcessingType are required." });
        }

        var entity = new DocumentCorrectionFeedback
        {
            DocumentProcessingRunId = request.DocumentProcessingRunId,
            ProcessingType = request.ProcessingType.Trim(),
            FieldName = request.FieldName?.Trim(),
            OriginalValue = request.OriginalValue,
            CorrectedValue = request.CorrectedValue,
            ReviewerNotes = request.ReviewerNotes?.Trim(),
            CreatedByUserId = GetCurrentUserId(),
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentCorrectionFeedback.Add(entity);
        await _context.SaveChangesAsync();
        return Ok();
    }

    [HttpPost("classification/suggest")]
    public async Task<ActionResult<List<DocumentClassificationSuggestionDto>>> SuggestClassificationLabels([FromForm] List<IFormFile> files)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (files == null || files.Count == 0)
        {
            return BadRequest(new { message = "At least one PDF file is required." });
        }

        var results = new List<DocumentClassificationSuggestionDto>();

        foreach (var file in files.Where(f => f.Length > 0))
        {
            var extractedText = await ExtractTextAsync(file);
            var suggestion = await _documentAiService.BuildClassificationSuggestionAsync(
                file.FileName,
                extractedText,
                HttpContext.RequestAborted);
            results.Add(suggestion);
        }

        return Ok(results);
    }

    [HttpPost("classification/test")]
    public async Task<ActionResult<DocumentClassificationTestResponse>> TestClassification([FromForm] IFormFile file)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "A document file is required." });
        }

        var templates = await _context.DocumentClassificationLabels
            .AsNoTracking()
            .Include(x => x.DocumentLabelSet)
            .Where(x => x.IsActive && x.DocumentLabelSet != null && x.DocumentLabelSet.IsActive)
            .Select(x => new ClassificationTemplate
            {
                DocumentClassificationLabelId = x.DocumentClassificationLabelId,
                ClassificationLabel = x.ClassificationLabel,
                ClassificationDescription = x.ClassificationDescription,
                ClassificationPrompt = x.ClassificationPrompt
            })
            .ToListAsync();

        var extractedText = await ExtractTextAsync(file);
        var consolidatedContent = $"File name: {file.FileName}\n\nContent:\n{extractedText}";
        var (label, score, explainability, bestTemplate) = ClassifyAgainstTemplates(consolidatedContent, templates);

        return Ok(new DocumentClassificationTestResponse
        {
            FileName = file.FileName,
            ClassificationLabel = label,
            ClassificationDescription = bestTemplate?.ClassificationDescription,
            ClassificationScore = score,
            ClassificationExplainability = explainability,
            DocumentClassificationLabelId = bestTemplate?.DocumentClassificationLabelId,
            TextPreview = extractedText.Length > 800 ? extractedText[..800] + "..." : extractedText
        });
    }

    [HttpPost("summarisation/preview")]
    public async Task<ActionResult<DocumentSummarisationPreviewResponse>> PreviewSummarisation([FromForm] IFormFile file, [FromForm] string prompt)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "A PDF file is required." });
        }

        if (string.IsNullOrWhiteSpace(prompt))
        {
            return BadRequest(new { message = "A summarisation prompt is required." });
        }

        var extractedText = await ExtractTextAsync(file);
        var summary = await _documentAiService.SummariseAsync(extractedText, prompt.Trim(), HttpContext.RequestAborted);

        return Ok(new DocumentSummarisationPreviewResponse
        {
            FileName = file.FileName,
            PromptUsed = prompt.Trim(),
            Summary = summary,
            TextPreview = extractedText.Length > 500 ? extractedText[..500] + "..." : extractedText
        });
    }

    [HttpPost("extraction/preview")]
    public async Task<ActionResult<DocumentExtractionPreviewResponse>> PreviewExtraction([FromForm] IFormFile file)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "A PDF file is required." });
        }

        var extractedText = await ExtractTextAsync(file);
        var suggestedFields = await _documentAiService.SuggestExtractionFieldsAsync(extractedText, HttpContext.RequestAborted);

        return Ok(new DocumentExtractionPreviewResponse
        {
            FileName = file.FileName,
            ExtractedText = extractedText,
            TextPreview = extractedText.Length > 800 ? extractedText[..800] + "..." : extractedText,
            SuggestedFields = suggestedFields
        });
    }

    [HttpPost("extraction/selection-suggest")]
    public async Task<ActionResult<List<DocumentExtractionSuggestedFieldDto>>> SuggestSelectionExtraction([FromBody] SuggestExtractionFromSelectionRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (string.IsNullOrWhiteSpace(request.SelectedText))
        {
            return BadRequest(new { message = "SelectedText is required." });
        }

        var suggestions = await _documentAiService.SuggestFieldsFromSelectionAsync(
            request.SelectedText.Trim(),
            request.ExtractedText?.Trim() ?? string.Empty,
            HttpContext.RequestAborted);

        return Ok(suggestions);
    }

    [HttpPost("email-processing/property-hub/trigger")]
    public async Task<ActionResult<TriggerPropertyHubEmailProcessingResponse>> TriggerPropertyHubEmailProcessing(
        [FromBody] TriggerPropertyHubEmailProcessingRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var functionUrl =
            _configuration["EmailProcessor:FunctionUrl"] ??
            Environment.GetEnvironmentVariable("EmailProcessor__FunctionUrl") ??
            _configuration["EmailProcessor_FunctionUrl"] ??
            Environment.GetEnvironmentVariable("EmailProcessor_FunctionUrl");
        var functionKey =
            _configuration["EmailProcessor:FunctionKey"] ??
            Environment.GetEnvironmentVariable("EmailProcessor__FunctionKey") ??
            _configuration["EmailProcessor_FunctionKey"] ??
            Environment.GetEnvironmentVariable("EmailProcessor_FunctionKey");

        functionUrl = functionUrl?.Trim();
        functionKey = functionKey?.Trim();

        if (string.IsNullOrWhiteSpace(functionUrl) || string.IsNullOrWhiteSpace(functionKey))
        {
            var missing = new List<string>();
            if (string.IsNullOrWhiteSpace(functionUrl))
            {
                missing.Add("EmailProcessor__FunctionUrl");
            }
            if (string.IsNullOrWhiteSpace(functionKey))
            {
                missing.Add("EmailProcessor__FunctionKey");
            }

            return StatusCode(500, new TriggerPropertyHubEmailProcessingResponse
            {
                Status = "error",
                Message = $"Email processor function configuration is missing: {string.Join(", ", missing)}."
            });
        }

        var endpoint = functionUrl.Contains("?", StringComparison.Ordinal)
            ? $"{functionUrl}&code={Uri.EscapeDataString(functionKey)}"
            : $"{functionUrl}?code={Uri.EscapeDataString(functionKey)}";

        var payload = new TriggerPropertyHubEmailProcessingRequest
        {
            MailboxUser = string.IsNullOrWhiteSpace(request.MailboxUser) ? null : request.MailboxUser.Trim(),
            MaxEmails = request.MaxEmails
        };

        var json = JsonSerializer.Serialize(payload);
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json")
        };

        var client = _httpClientFactory.CreateClient();
        using var response = await client.SendAsync(httpRequest, HttpContext.RequestAborted);
        var rawContent = await response.Content.ReadAsStringAsync(HttpContext.RequestAborted);

        if (!response.IsSuccessStatusCode)
        {
            return StatusCode((int)response.StatusCode, new TriggerPropertyHubEmailProcessingResponse
            {
                Status = "error",
                Message = $"Email processor function returned {(int)response.StatusCode}.",
                ProcessingResult = rawContent
            });
        }

        object resultPayload;
        try
        {
            resultPayload = JsonSerializer.Deserialize<object>(rawContent) ?? rawContent;
        }
        catch
        {
            resultPayload = rawContent;
        }

        return Ok(new TriggerPropertyHubEmailProcessingResponse
        {
            Status = "ok",
            Message = "Email processing trigger completed.",
            ProcessingResult = resultPayload
        });
    }

    private async Task<UserDto?> GetCurrentUserAsync()
    {
        var userId = GetCurrentUserId();
        if (userId == null) return null;
        return await _authService.GetCurrentUserAsync(userId.Value);
    }

    private int? GetCurrentUserId()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (string.IsNullOrWhiteSpace(userIdClaim) || !int.TryParse(userIdClaim, out var userId))
        {
            return null;
        }

        return userId;
    }

    private static bool HasPropertyHubAccess(UserDto user)
    {
        if (user.IsGlobalAdmin) return true;

        return user.WorkstreamAccess.Any(wa =>
            wa.WorkstreamName.Equals("Property Hub", StringComparison.OrdinalIgnoreCase) ||
            wa.WorkstreamName.Contains("Property", StringComparison.OrdinalIgnoreCase));
    }

    private static DocumentLabelSetDto MapLabelSet(DocumentLabelSet x)
    {
        return new DocumentLabelSetDto
        {
            DocumentLabelSetId = x.DocumentLabelSetId,
            LabelSetName = x.LabelSetName,
            LabelSetDescription = x.LabelSetDescription,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate,
            Labels = x.ClassificationLabels
                .OrderBy(y => y.DocumentClassificationLabelId)
                .Select(MapClassificationLabel)
                .ToList()
        };
    }

    private static DocumentClassificationLabelDto MapClassificationLabel(DocumentClassificationLabel x)
    {
        return new DocumentClassificationLabelDto
        {
            DocumentClassificationLabelId = x.DocumentClassificationLabelId,
            DocumentLabelSetId = x.DocumentLabelSetId,
            ClassificationLabel = x.ClassificationLabel,
            ClassificationDescription = x.ClassificationDescription,
            ClassificationPrompt = x.ClassificationPrompt,
            SeedDocumentName = x.SeedDocumentName,
            IsAutoGenerated = x.IsAutoGenerated,
            IsActive = x.IsActive
        };
    }

    private static DocumentSummarisationTemplateDto MapSummarisationTemplate(DocumentSummarisationTemplate x)
    {
        return new DocumentSummarisationTemplateDto
        {
            DocumentSummarisationTemplateId = x.DocumentSummarisationTemplateId,
            SummarisationName = x.SummarisationName,
            SummarisationDescription = x.SummarisationDescription,
            SummarisationPrompt = x.SummarisationPrompt,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate
        };
    }

    private static DocumentExtractionTemplateDto MapExtractionTemplate(DocumentExtractionTemplate x)
    {
        return new DocumentExtractionTemplateDto
        {
            DocumentExtractionTemplateId = x.DocumentExtractionTemplateId,
            ExtractionTemplateName = x.ExtractionTemplateName,
            ExtractionTemplateDescription = x.ExtractionTemplateDescription,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate,
            Fields = x.ExtractionFields
                .OrderBy(y => y.DocumentExtractionFieldId)
                .Select(MapExtractionField)
                .ToList()
        };
    }

    private static DocumentExtractionFieldDto MapExtractionField(DocumentExtractionField x)
    {
        return new DocumentExtractionFieldDto
        {
            DocumentExtractionFieldId = x.DocumentExtractionFieldId,
            DocumentExtractionTemplateId = x.DocumentExtractionTemplateId,
            FieldName = x.FieldName,
            ExampleValue = x.ExampleValue,
            AnchorTextBefore = x.AnchorTextBefore,
            AnchorTextAfter = x.AnchorTextAfter,
            FieldExtractionPrompt = x.FieldExtractionPrompt,
            PageNumber = x.PageNumber,
            BoundingBoxJson = x.BoundingBoxJson,
            IsActive = x.IsActive
        };
    }

    private static async Task<string> ExtractTextAsync(IFormFile file)
    {
        var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
        if (extension == ".pdf")
        {
            await using var stream = file.OpenReadStream();
            var text = DocumentHubAiHelper.ExtractTextFromPdf(stream);
            return DocumentHubAiHelper.NormalizeWhitespace(text);
        }

        if (extension is ".txt" or ".csv" or ".json" or ".xml" or ".log" or ".md")
        {
            using var reader = new StreamReader(file.OpenReadStream());
            var raw = await reader.ReadToEndAsync();
            return DocumentHubAiHelper.NormalizeWhitespace(raw);
        }

        return string.Empty;
    }

    private static (string Label, double Score, string Explainability, ClassificationTemplate? BestTemplate) ClassifyAgainstTemplates(
        string content,
        List<ClassificationTemplate> templates)
    {
        if (templates.Count == 0 || string.IsNullOrWhiteSpace(content))
        {
            return ("Unclassified", 0, "No active classification templates or no usable content was available.", null);
        }

        var contentTokens = Tokenize(content);
        if (contentTokens.Count == 0)
        {
            return ("Unclassified", 0, "Content did not contain enough meaningful tokens for template matching.", null);
        }

        ClassificationTemplate? bestTemplate = null;
        double bestScore = 0;
        var bestOverlapTerms = new List<string>();

        foreach (var template in templates)
        {
            var templateText = $"{template.ClassificationLabel} {template.ClassificationDescription} {template.ClassificationPrompt}";
            var templateTokens = Tokenize(templateText);
            if (templateTokens.Count == 0)
            {
                continue;
            }

            var overlapTerms = templateTokens.Intersect(contentTokens, StringComparer.OrdinalIgnoreCase).ToList();
            var overlap = overlapTerms.Count;
            var score = (double)overlap / Math.Max(1, templateTokens.Count);
            if (score > bestScore)
            {
                bestScore = score;
                bestTemplate = template;
                bestOverlapTerms = overlapTerms.Take(8).ToList();
            }
        }

        if (bestTemplate == null || bestScore < 0.08)
        {
            var explanation = bestTemplate == null
                ? "No template produced a meaningful lexical overlap with the document content."
                : $"Best template overlap score {Math.Round(bestScore, 4)} is below threshold 0.08. " +
                  $"Closest template was '{bestTemplate.ClassificationLabel}' with terms: {string.Join(", ", bestOverlapTerms.DefaultIfEmpty("none"))}.";
            return ("Unclassified", Math.Round(bestScore, 4), explanation, null);
        }

        var explainability =
            $"Matched template '{bestTemplate.ClassificationLabel}' with score {Math.Round(bestScore, 4)} " +
            $"using overlap terms: {string.Join(", ", bestOverlapTerms.DefaultIfEmpty("none"))}. " +
            "Score is computed as overlap terms divided by template token count.";

        return (bestTemplate.ClassificationLabel, Math.Round(bestScore, 4), explainability, bestTemplate);
    }

    private static HashSet<string> Tokenize(string value)
    {
        return Regex.Matches(value.ToLowerInvariant(), "[a-z0-9]{3,}")
            .Select(m => m.Value)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private sealed class ClassificationTemplate
    {
        public int DocumentClassificationLabelId { get; set; }
        public string ClassificationLabel { get; set; } = string.Empty;
        public string? ClassificationDescription { get; set; }
        public string ClassificationPrompt { get; set; } = string.Empty;
    }
}
