using System.Security.Claims;
using backend.DTOs;
using backend.Models;
using backend.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace backend.Controllers;

[ApiController]
[Route("api/document-hub")]
[Authorize]
public class DocumentHubController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly IAuthService _authService;
    private readonly IDocumentAiService _documentAiService;

    public DocumentHubController(ApplicationDbContext context, IAuthService authService, IDocumentAiService documentAiService)
    {
        _context = context;
        _authService = authService;
        _documentAiService = documentAiService;
    }

    [HttpGet("label-sets")]
    public async Task<ActionResult<List<DocumentLabelSetDto>>> GetLabelSets()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentLabelSets
            .AsNoTracking()
            .Include(x => x.ClassificationLabels)
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapLabelSet).ToList());
    }

    [HttpPost("label-sets")]
    public async Task<ActionResult<DocumentLabelSetDto>> CreateLabelSet([FromBody] CreateDocumentLabelSetRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.LabelSetName))
        {
            return BadRequest(new { message = "Label set name is required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentLabelSet
        {
            LabelSetName = request.LabelSetName.Trim(),
            LabelSetDescription = request.LabelSetDescription?.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentLabelSets.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapLabelSet(entity));
    }

    [HttpPost("label-sets/{labelSetId:int}/labels")]
    public async Task<ActionResult<DocumentClassificationLabelDto>> CreateClassificationLabel(int labelSetId, [FromBody] CreateDocumentClassificationLabelRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.ClassificationLabel) || string.IsNullOrWhiteSpace(request.ClassificationPrompt))
        {
            return BadRequest(new { message = "Classification label and prompt are required." });
        }

        var labelSet = await _context.DocumentLabelSets.FirstOrDefaultAsync(x => x.DocumentLabelSetId == labelSetId);
        if (labelSet == null) return NotFound(new { message = "Label set not found." });

        var userId = GetCurrentUserId();
        var entity = new DocumentClassificationLabel
        {
            DocumentLabelSetId = labelSetId,
            ClassificationLabel = request.ClassificationLabel.Trim(),
            ClassificationDescription = request.ClassificationDescription?.Trim(),
            ClassificationPrompt = request.ClassificationPrompt.Trim(),
            SeedDocumentName = request.SeedDocumentName?.Trim(),
            SeedDocumentHash = request.SeedDocumentHash?.Trim(),
            IsAutoGenerated = request.IsAutoGenerated,
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentClassificationLabels.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapClassificationLabel(entity));
    }

    [HttpGet("summarisation-templates")]
    public async Task<ActionResult<List<DocumentSummarisationTemplateDto>>> GetSummarisationTemplates()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentSummarisationTemplates
            .AsNoTracking()
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapSummarisationTemplate).ToList());
    }

    [HttpPost("summarisation-templates")]
    public async Task<ActionResult<DocumentSummarisationTemplateDto>> CreateSummarisationTemplate([FromBody] CreateDocumentSummarisationTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.SummarisationName) || string.IsNullOrWhiteSpace(request.SummarisationPrompt))
        {
            return BadRequest(new { message = "Summarisation name and prompt are required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentSummarisationTemplate
        {
            SummarisationName = request.SummarisationName.Trim(),
            SummarisationDescription = request.SummarisationDescription?.Trim(),
            SummarisationPrompt = request.SummarisationPrompt.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentSummarisationTemplates.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapSummarisationTemplate(entity));
    }

    [HttpPut("summarisation-templates/{templateId:int}")]
    public async Task<ActionResult<DocumentSummarisationTemplateDto>> UpdateSummarisationTemplate(int templateId, [FromBody] UpdateDocumentSummarisationTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        var entity = await _context.DocumentSummarisationTemplates.FirstOrDefaultAsync(x => x.DocumentSummarisationTemplateId == templateId);
        if (entity == null)
        {
            return NotFound(new { message = "Summarisation template not found." });
        }

        if (request.SummarisationName != null)
        {
            entity.SummarisationName = request.SummarisationName.Trim();
        }

        if (request.SummarisationDescription != null)
        {
            entity.SummarisationDescription = request.SummarisationDescription.Trim();
        }

        if (request.SummarisationPrompt != null)
        {
            entity.SummarisationPrompt = request.SummarisationPrompt.Trim();
        }

        if (request.IsActive.HasValue)
        {
            entity.IsActive = request.IsActive.Value;
        }

        entity.UpdatedByUserId = GetCurrentUserId();
        entity.UpdatedDate = DateTime.UtcNow;

        await _context.SaveChangesAsync();
        return Ok(MapSummarisationTemplate(entity));
    }

    [HttpGet("extraction-templates")]
    public async Task<ActionResult<List<DocumentExtractionTemplateDto>>> GetExtractionTemplates()
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        var items = await _context.DocumentExtractionTemplates
            .AsNoTracking()
            .Include(x => x.ExtractionFields)
            .OrderByDescending(x => x.CreatedDate)
            .ToListAsync();

        return Ok(items.Select(MapExtractionTemplate).ToList());
    }

    [HttpPost("extraction-templates")]
    public async Task<ActionResult<DocumentExtractionTemplateDto>> CreateExtractionTemplate([FromBody] CreateDocumentExtractionTemplateRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.ExtractionTemplateName))
        {
            return BadRequest(new { message = "Extraction template name is required." });
        }

        var userId = GetCurrentUserId();
        var entity = new DocumentExtractionTemplate
        {
            ExtractionTemplateName = request.ExtractionTemplateName.Trim(),
            ExtractionTemplateDescription = request.ExtractionTemplateDescription?.Trim(),
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentExtractionTemplates.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapExtractionTemplate(entity));
    }

    [HttpPost("extraction-templates/{templateId:int}/fields")]
    public async Task<ActionResult<DocumentExtractionFieldDto>> CreateExtractionField(int templateId, [FromBody] CreateDocumentExtractionFieldRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (string.IsNullOrWhiteSpace(request.FieldName))
        {
            return BadRequest(new { message = "Field name is required." });
        }

        var template = await _context.DocumentExtractionTemplates.FirstOrDefaultAsync(x => x.DocumentExtractionTemplateId == templateId);
        if (template == null) return NotFound(new { message = "Extraction template not found." });

        var userId = GetCurrentUserId();
        var entity = new DocumentExtractionField
        {
            DocumentExtractionTemplateId = templateId,
            FieldName = request.FieldName.Trim(),
            ExampleValue = request.ExampleValue?.Trim(),
            AnchorTextBefore = request.AnchorTextBefore?.Trim(),
            AnchorTextAfter = request.AnchorTextAfter?.Trim(),
            FieldExtractionPrompt = request.FieldExtractionPrompt?.Trim(),
            PageNumber = request.PageNumber,
            BoundingBoxJson = request.BoundingBoxJson,
            IsActive = true,
            CreatedByUserId = userId,
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentExtractionFields.Add(entity);
        await _context.SaveChangesAsync();

        return Ok(MapExtractionField(entity));
    }

    [HttpPost("correction-feedback")]
    public async Task<ActionResult> CreateCorrectionFeedback([FromBody] CreateDocumentCorrectionFeedbackRequest request)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (request.DocumentProcessingRunId <= 0 || string.IsNullOrWhiteSpace(request.ProcessingType))
        {
            return BadRequest(new { message = "DocumentProcessingRunId and ProcessingType are required." });
        }

        var entity = new DocumentCorrectionFeedback
        {
            DocumentProcessingRunId = request.DocumentProcessingRunId,
            ProcessingType = request.ProcessingType.Trim(),
            FieldName = request.FieldName?.Trim(),
            OriginalValue = request.OriginalValue,
            CorrectedValue = request.CorrectedValue,
            ReviewerNotes = request.ReviewerNotes?.Trim(),
            CreatedByUserId = GetCurrentUserId(),
            CreatedDate = DateTime.UtcNow
        };

        _context.DocumentCorrectionFeedback.Add(entity);
        await _context.SaveChangesAsync();
        return Ok();
    }

    [HttpPost("classification/suggest")]
    public async Task<ActionResult<List<DocumentClassificationSuggestionDto>>> SuggestClassificationLabels([FromForm] List<IFormFile> files)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!_authService.HasPropertyHubAdminAccess(currentUser)) return Forbid("Access denied: Property Hub Admin permission required.");

        if (files == null || files.Count == 0)
        {
            return BadRequest(new { message = "At least one PDF file is required." });
        }

        var results = new List<DocumentClassificationSuggestionDto>();

        foreach (var file in files.Where(f => f.Length > 0))
        {
            var extractedText = await ExtractTextAsync(file);
            var suggestion = await _documentAiService.BuildClassificationSuggestionAsync(
                file.FileName,
                extractedText,
                HttpContext.RequestAborted);
            results.Add(suggestion);
        }

        return Ok(results);
    }

    [HttpPost("summarisation/preview")]
    public async Task<ActionResult<DocumentSummarisationPreviewResponse>> PreviewSummarisation([FromForm] IFormFile file, [FromForm] string prompt)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "A PDF file is required." });
        }

        if (string.IsNullOrWhiteSpace(prompt))
        {
            return BadRequest(new { message = "A summarisation prompt is required." });
        }

        var extractedText = await ExtractTextAsync(file);
        var summary = await _documentAiService.SummariseAsync(extractedText, prompt.Trim(), HttpContext.RequestAborted);

        return Ok(new DocumentSummarisationPreviewResponse
        {
            FileName = file.FileName,
            PromptUsed = prompt.Trim(),
            Summary = summary,
            TextPreview = extractedText.Length > 500 ? extractedText[..500] + "..." : extractedText
        });
    }

    [HttpPost("extraction/preview")]
    public async Task<ActionResult<DocumentExtractionPreviewResponse>> PreviewExtraction([FromForm] IFormFile file)
    {
        var currentUser = await GetCurrentUserAsync();
        if (currentUser == null) return Unauthorized();
        if (!HasPropertyHubAccess(currentUser)) return Forbid("Access denied: Property Hub access required.");

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "A PDF file is required." });
        }

        var extractedText = await ExtractTextAsync(file);
        var suggestedFields = await _documentAiService.SuggestExtractionFieldsAsync(extractedText, HttpContext.RequestAborted);

        return Ok(new DocumentExtractionPreviewResponse
        {
            FileName = file.FileName,
            ExtractedText = extractedText,
            TextPreview = extractedText.Length > 800 ? extractedText[..800] + "..." : extractedText,
            SuggestedFields = suggestedFields
        });
    }

    private async Task<UserDto?> GetCurrentUserAsync()
    {
        var userId = GetCurrentUserId();
        if (userId == null) return null;
        return await _authService.GetCurrentUserAsync(userId.Value);
    }

    private int? GetCurrentUserId()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (string.IsNullOrWhiteSpace(userIdClaim) || !int.TryParse(userIdClaim, out var userId))
        {
            return null;
        }

        return userId;
    }

    private static bool HasPropertyHubAccess(UserDto user)
    {
        if (user.IsGlobalAdmin) return true;

        return user.WorkstreamAccess.Any(wa =>
            wa.WorkstreamName.Equals("Property Hub", StringComparison.OrdinalIgnoreCase) ||
            wa.WorkstreamName.Contains("Property", StringComparison.OrdinalIgnoreCase));
    }

    private static DocumentLabelSetDto MapLabelSet(DocumentLabelSet x)
    {
        return new DocumentLabelSetDto
        {
            DocumentLabelSetId = x.DocumentLabelSetId,
            LabelSetName = x.LabelSetName,
            LabelSetDescription = x.LabelSetDescription,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate,
            Labels = x.ClassificationLabels
                .OrderBy(y => y.DocumentClassificationLabelId)
                .Select(MapClassificationLabel)
                .ToList()
        };
    }

    private static DocumentClassificationLabelDto MapClassificationLabel(DocumentClassificationLabel x)
    {
        return new DocumentClassificationLabelDto
        {
            DocumentClassificationLabelId = x.DocumentClassificationLabelId,
            DocumentLabelSetId = x.DocumentLabelSetId,
            ClassificationLabel = x.ClassificationLabel,
            ClassificationDescription = x.ClassificationDescription,
            ClassificationPrompt = x.ClassificationPrompt,
            SeedDocumentName = x.SeedDocumentName,
            IsAutoGenerated = x.IsAutoGenerated,
            IsActive = x.IsActive
        };
    }

    private static DocumentSummarisationTemplateDto MapSummarisationTemplate(DocumentSummarisationTemplate x)
    {
        return new DocumentSummarisationTemplateDto
        {
            DocumentSummarisationTemplateId = x.DocumentSummarisationTemplateId,
            SummarisationName = x.SummarisationName,
            SummarisationDescription = x.SummarisationDescription,
            SummarisationPrompt = x.SummarisationPrompt,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate
        };
    }

    private static DocumentExtractionTemplateDto MapExtractionTemplate(DocumentExtractionTemplate x)
    {
        return new DocumentExtractionTemplateDto
        {
            DocumentExtractionTemplateId = x.DocumentExtractionTemplateId,
            ExtractionTemplateName = x.ExtractionTemplateName,
            ExtractionTemplateDescription = x.ExtractionTemplateDescription,
            IsActive = x.IsActive,
            CreatedDate = x.CreatedDate,
            Fields = x.ExtractionFields
                .OrderBy(y => y.DocumentExtractionFieldId)
                .Select(MapExtractionField)
                .ToList()
        };
    }

    private static DocumentExtractionFieldDto MapExtractionField(DocumentExtractionField x)
    {
        return new DocumentExtractionFieldDto
        {
            DocumentExtractionFieldId = x.DocumentExtractionFieldId,
            DocumentExtractionTemplateId = x.DocumentExtractionTemplateId,
            FieldName = x.FieldName,
            ExampleValue = x.ExampleValue,
            AnchorTextBefore = x.AnchorTextBefore,
            AnchorTextAfter = x.AnchorTextAfter,
            FieldExtractionPrompt = x.FieldExtractionPrompt,
            PageNumber = x.PageNumber,
            BoundingBoxJson = x.BoundingBoxJson,
            IsActive = x.IsActive
        };
    }

    private static async Task<string> ExtractTextAsync(IFormFile file)
    {
        var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
        if (extension != ".pdf")
        {
            return string.Empty;
        }

        await using var stream = file.OpenReadStream();
        var text = DocumentHubAiHelper.ExtractTextFromPdf(stream);
        return DocumentHubAiHelper.NormalizeWhitespace(text);
    }
}
