-- Check actual column names in PropertyGroup and Property tables

-- PropertyGroup table
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblPropertyGroup'
ORDER BY ORDINAL_POSITION;

-- Property table
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblProperty'
ORDER BY ORDINAL_POSITION;
