-- Check actual column names for all tables that are showing errors

-- Tenant table
SELECT 'tblTenant' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblTenant'
ORDER BY ORDINAL_POSITION;

-- Tenancy table
SELECT 'tblTenancy' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblTenancy'
ORDER BY ORDINAL_POSITION;

-- TagType table
SELECT 'tblTagType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblTagType'
ORDER BY ORDINAL_POSITION;

-- TagLog table
SELECT 'tblTagLog' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblTagLog'
ORDER BY ORDINAL_POSITION;

-- JournalType table
SELECT 'tblJournalType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblJournalType'
ORDER BY ORDINAL_POSITION;

-- JournalSubType table
SELECT 'tblJournalSubType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblJournalSubType'
ORDER BY ORDINAL_POSITION;

-- JournalLog table
SELECT 'tblJournalLog' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblJournalLog'
ORDER BY ORDINAL_POSITION;

-- ContactLogType table
SELECT 'tblContactLogType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblContactLogType'
ORDER BY ORDINAL_POSITION;

-- ContactLog table
SELECT 'tblContactLog' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblContactLog'
ORDER BY ORDINAL_POSITION;

-- ContactLogAttachment table (if exists)
SELECT 'tblContactLogAttachment' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblContactLogAttachment'
ORDER BY ORDINAL_POSITION;
