-- COMPREHENSIVE DATABASE SCHEMA CHECK
-- Run this query to get ALL tables and columns for verification

-- Get all tables first
SELECT 'TABLES' AS Info, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Get all columns for all tables
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Specific check for tables we know exist but might have issues
SELECT 'tblJournalLogAttachment' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblJournalLogAttachment'
ORDER BY ORDINAL_POSITION;

SELECT 'tblUser' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblUser'
ORDER BY ORDINAL_POSITION;

SELECT 'tblRoleType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblRoleType'
ORDER BY ORDINAL_POSITION;

SELECT 'tblUserRole' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblUserRole'
ORDER BY ORDINAL_POSITION;

SELECT 'tblWorkstream' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblWorkstream'
ORDER BY ORDINAL_POSITION;

SELECT 'tblWorkstreamUsers' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblWorkstreamUsers'
ORDER BY ORDINAL_POSITION;

SELECT 'tblPermissionType' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblPermissionType'
ORDER BY ORDINAL_POSITION;

SELECT 'tblAuditLog' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tblAuditLog'
ORDER BY ORDINAL_POSITION;
