-- Document Hub core schema (global assets + correction-driven learning)
-- SQL Server

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentlabelset')
BEGIN
    CREATE TABLE tbldocumentlabelset (
        DocumentLabelSetId INT IDENTITY(1,1) PRIMARY KEY,
        LabelSetName NVARCHAR(200) NOT NULL,
        LabelSetDescription NVARCHAR(2000) NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_tbldocumentlabelset_IsActive DEFAULT (1),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentlabelset_CreatedDate DEFAULT (SYSUTCDATETIME()),
        UpdatedByUserId INT NULL,
        UpdatedDate DATETIME2 NULL
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentclassificationlabel')
BEGIN
    CREATE TABLE tbldocumentclassificationlabel (
        DocumentClassificationLabelId INT IDENTITY(1,1) PRIMARY KEY,
        DocumentLabelSetId INT NOT NULL,
        ClassificationLabel NVARCHAR(80) NOT NULL,
        ClassificationDescription NVARCHAR(2000) NULL,
        ClassificationPrompt NVARCHAR(MAX) NOT NULL,
        SeedDocumentName NVARCHAR(260) NULL,
        SeedDocumentHash NVARCHAR(128) NULL,
        IsAutoGenerated BIT NOT NULL CONSTRAINT DF_tbldocumentclassificationlabel_IsAutoGenerated DEFAULT (1),
        IsActive BIT NOT NULL CONSTRAINT DF_tbldocumentclassificationlabel_IsActive DEFAULT (1),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentclassificationlabel_CreatedDate DEFAULT (SYSUTCDATETIME()),
        UpdatedByUserId INT NULL,
        UpdatedDate DATETIME2 NULL,
        CONSTRAINT FK_tbldocumentclassificationlabel_tbldocumentlabelset
            FOREIGN KEY (DocumentLabelSetId) REFERENCES tbldocumentlabelset(DocumentLabelSetId)
    );

    CREATE INDEX IX_tbldocumentclassificationlabel_DocumentLabelSetId
        ON tbldocumentclassificationlabel (DocumentLabelSetId);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentsummarisationtemplate')
BEGIN
    CREATE TABLE tbldocumentsummarisationtemplate (
        DocumentSummarisationTemplateId INT IDENTITY(1,1) PRIMARY KEY,
        SummarisationName NVARCHAR(200) NOT NULL,
        SummarisationDescription NVARCHAR(2000) NULL,
        SummarisationPrompt NVARCHAR(MAX) NOT NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_tbldocumentsummarisationtemplate_IsActive DEFAULT (1),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentsummarisationtemplate_CreatedDate DEFAULT (SYSUTCDATETIME()),
        UpdatedByUserId INT NULL,
        UpdatedDate DATETIME2 NULL
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentextractiontemplate')
BEGIN
    CREATE TABLE tbldocumentextractiontemplate (
        DocumentExtractionTemplateId INT IDENTITY(1,1) PRIMARY KEY,
        ExtractionTemplateName NVARCHAR(200) NOT NULL,
        ExtractionTemplateDescription NVARCHAR(2000) NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_tbldocumentextractiontemplate_IsActive DEFAULT (1),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentextractiontemplate_CreatedDate DEFAULT (SYSUTCDATETIME()),
        UpdatedByUserId INT NULL,
        UpdatedDate DATETIME2 NULL
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentextractionfield')
BEGIN
    CREATE TABLE tbldocumentextractionfield (
        DocumentExtractionFieldId INT IDENTITY(1,1) PRIMARY KEY,
        DocumentExtractionTemplateId INT NOT NULL,
        FieldName NVARCHAR(200) NOT NULL,
        ExampleValue NVARCHAR(2000) NULL,
        AnchorTextBefore NVARCHAR(1000) NULL,
        AnchorTextAfter NVARCHAR(1000) NULL,
        FieldExtractionPrompt NVARCHAR(MAX) NULL,
        PageNumber INT NULL,
        BoundingBoxJson NVARCHAR(MAX) NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_tbldocumentextractionfield_IsActive DEFAULT (1),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentextractionfield_CreatedDate DEFAULT (SYSUTCDATETIME()),
        UpdatedByUserId INT NULL,
        UpdatedDate DATETIME2 NULL,
        CONSTRAINT FK_tbldocumentextractionfield_tbldocumentextractiontemplate
            FOREIGN KEY (DocumentExtractionTemplateId) REFERENCES tbldocumentextractiontemplate(DocumentExtractionTemplateId)
    );

    CREATE INDEX IX_tbldocumentextractionfield_DocumentExtractionTemplateId
        ON tbldocumentextractionfield (DocumentExtractionTemplateId);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentprocessingrun')
BEGIN
    CREATE TABLE tbldocumentprocessingrun (
        DocumentProcessingRunId BIGINT IDENTITY(1,1) PRIMARY KEY,
        SourceModule NVARCHAR(100) NULL,
        SourceRecordId NVARCHAR(120) NULL,
        UploadedFileName NVARCHAR(260) NOT NULL,
        UploadedFileHash NVARCHAR(128) NULL,
        ProcessingType NVARCHAR(50) NOT NULL, -- classification | summarisation | extraction
        AssetType NVARCHAR(50) NOT NULL,      -- label-set | summarisation-template | extraction-template
        AssetId INT NOT NULL,
        ResultJson NVARCHAR(MAX) NULL,
        ConfidenceScore DECIMAL(5,4) NULL,
        Status NVARCHAR(40) NOT NULL CONSTRAINT DF_tbldocumentprocessingrun_Status DEFAULT ('Completed'),
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentprocessingrun_CreatedDate DEFAULT (SYSUTCDATETIME())
    );

    CREATE INDEX IX_tbldocumentprocessingrun_AssetType_AssetId
        ON tbldocumentprocessingrun (AssetType, AssetId);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tbldocumentcorrectionfeedback')
BEGIN
    CREATE TABLE tbldocumentcorrectionfeedback (
        DocumentCorrectionFeedbackId BIGINT IDENTITY(1,1) PRIMARY KEY,
        DocumentProcessingRunId BIGINT NOT NULL,
        ProcessingType NVARCHAR(50) NOT NULL,
        FieldName NVARCHAR(200) NULL,
        OriginalValue NVARCHAR(MAX) NULL,
        CorrectedValue NVARCHAR(MAX) NULL,
        ReviewerNotes NVARCHAR(2000) NULL,
        CreatedByUserId INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_tbldocumentcorrectionfeedback_CreatedDate DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_tbldocumentcorrectionfeedback_tbldocumentprocessingrun
            FOREIGN KEY (DocumentProcessingRunId) REFERENCES tbldocumentprocessingrun(DocumentProcessingRunId)
    );

    CREATE INDEX IX_tbldocumentcorrectionfeedback_DocumentProcessingRunId
        ON tbldocumentcorrectionfeedback (DocumentProcessingRunId);
END;
GO
