-- Run this to see ALL tables in your database

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Also check for tables with "User" or "Role" in the name
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
  AND (TABLE_NAME LIKE '%User%' OR TABLE_NAME LIKE '%Role%')
ORDER BY TABLE_NAME;
