namespace backend.DTOs;

public class DocumentClassificationLabelDto
{
    public int DocumentClassificationLabelId { get; set; }
    public int DocumentLabelSetId { get; set; }
    public string ClassificationLabel { get; set; } = string.Empty;
    public string? ClassificationDescription { get; set; }
    public string ClassificationPrompt { get; set; } = string.Empty;
    public string? SeedDocumentName { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsActive { get; set; }
}

public class DocumentLabelSetDto
{
    public int DocumentLabelSetId { get; set; }
    public string LabelSetName { get; set; } = string.Empty;
    public string? LabelSetDescription { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public List<DocumentClassificationLabelDto> Labels { get; set; } = new();
}

public class CreateDocumentLabelSetRequest
{
    public string LabelSetName { get; set; } = string.Empty;
    public string? LabelSetDescription { get; set; }
}

public class CreateDocumentClassificationLabelRequest
{
    public string ClassificationLabel { get; set; } = string.Empty;
    public string? ClassificationDescription { get; set; }
    public string ClassificationPrompt { get; set; } = string.Empty;
    public string? SeedDocumentName { get; set; }
    public string? SeedDocumentHash { get; set; }
    public bool IsAutoGenerated { get; set; } = true;
}

public class DocumentSummarisationTemplateDto
{
    public int DocumentSummarisationTemplateId { get; set; }
    public string SummarisationName { get; set; } = string.Empty;
    public string? SummarisationDescription { get; set; }
    public string SummarisationPrompt { get; set; } = string.Empty;
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
}

public class CreateDocumentSummarisationTemplateRequest
{
    public string SummarisationName { get; set; } = string.Empty;
    public string? SummarisationDescription { get; set; }
    public string SummarisationPrompt { get; set; } = string.Empty;
}

public class UpdateDocumentSummarisationTemplateRequest
{
    public string? SummarisationName { get; set; }
    public string? SummarisationDescription { get; set; }
    public string? SummarisationPrompt { get; set; }
    public bool? IsActive { get; set; }
}

public class DocumentExtractionFieldDto
{
    public int DocumentExtractionFieldId { get; set; }
    public int DocumentExtractionTemplateId { get; set; }
    public string FieldName { get; set; } = string.Empty;
    public string? ExampleValue { get; set; }
    public string? AnchorTextBefore { get; set; }
    public string? AnchorTextAfter { get; set; }
    public string? FieldExtractionPrompt { get; set; }
    public int? PageNumber { get; set; }
    public string? BoundingBoxJson { get; set; }
    public bool IsActive { get; set; }
}

public class DocumentExtractionTemplateDto
{
    public int DocumentExtractionTemplateId { get; set; }
    public string ExtractionTemplateName { get; set; } = string.Empty;
    public string? ExtractionTemplateDescription { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public List<DocumentExtractionFieldDto> Fields { get; set; } = new();
}

public class CreateDocumentExtractionTemplateRequest
{
    public string ExtractionTemplateName { get; set; } = string.Empty;
    public string? ExtractionTemplateDescription { get; set; }
}

public class CreateDocumentExtractionFieldRequest
{
    public string FieldName { get; set; } = string.Empty;
    public string? ExampleValue { get; set; }
    public string? AnchorTextBefore { get; set; }
    public string? AnchorTextAfter { get; set; }
    public string? FieldExtractionPrompt { get; set; }
    public int? PageNumber { get; set; }
    public string? BoundingBoxJson { get; set; }
}

public class CreateDocumentCorrectionFeedbackRequest
{
    public long DocumentProcessingRunId { get; set; }
    public string ProcessingType { get; set; } = string.Empty;
    public string? FieldName { get; set; }
    public string? OriginalValue { get; set; }
    public string? CorrectedValue { get; set; }
    public string? ReviewerNotes { get; set; }
}

public class DocumentClassificationSuggestionDto
{
    public string FileName { get; set; } = string.Empty;
    public string SuggestedLabel { get; set; } = string.Empty;
    public string SuggestedDescription { get; set; } = string.Empty;
    public string SuggestedPrompt { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
}

public class DocumentSummarisationPreviewResponse
{
    public string FileName { get; set; } = string.Empty;
    public string PromptUsed { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
}

public class DocumentExtractionPreviewResponse
{
    public string FileName { get; set; } = string.Empty;
    public string ExtractedText { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
}
