namespace backend.DTOs;

public class DocumentClassificationLabelDto
{
    public int DocumentClassificationLabelId { get; set; }
    public int DocumentLabelSetId { get; set; }
    public string ClassificationLabel { get; set; } = string.Empty;
    public string? ClassificationDescription { get; set; }
    public string ClassificationPrompt { get; set; } = string.Empty;
    public string? SeedDocumentName { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsActive { get; set; }
}

public class DocumentLabelSetDto
{
    public int DocumentLabelSetId { get; set; }
    public string LabelSetName { get; set; } = string.Empty;
    public string? LabelSetDescription { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public List<DocumentClassificationLabelDto> Labels { get; set; } = new();
}

public class CreateDocumentLabelSetRequest
{
    public string LabelSetName { get; set; } = string.Empty;
    public string? LabelSetDescription { get; set; }
}

public class UpdateDocumentLabelSetRequest
{
    public string? LabelSetName { get; set; }
    public string? LabelSetDescription { get; set; }
    public bool? IsActive { get; set; }
    public List<UpdateDocumentClassificationLabelRequest>? Labels { get; set; }
}

public class CreateDocumentClassificationLabelRequest
{
    public string ClassificationLabel { get; set; } = string.Empty;
    public string? ClassificationDescription { get; set; }
    public string ClassificationPrompt { get; set; } = string.Empty;
    public string? SeedDocumentName { get; set; }
    public string? SeedDocumentHash { get; set; }
    public bool IsAutoGenerated { get; set; } = true;
}

public class UpdateDocumentClassificationLabelRequest
{
    public string ClassificationLabel { get; set; } = string.Empty;
    public string? ClassificationDescription { get; set; }
    public string ClassificationPrompt { get; set; } = string.Empty;
    public string? SeedDocumentName { get; set; }
    public string? SeedDocumentHash { get; set; }
    public bool IsAutoGenerated { get; set; } = true;
    public bool IsActive { get; set; } = true;
}

public class DocumentSummarisationTemplateDto
{
    public int DocumentSummarisationTemplateId { get; set; }
    public string SummarisationName { get; set; } = string.Empty;
    public string? SummarisationDescription { get; set; }
    public string SummarisationPrompt { get; set; } = string.Empty;
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
}

public class CreateDocumentSummarisationTemplateRequest
{
    public string SummarisationName { get; set; } = string.Empty;
    public string? SummarisationDescription { get; set; }
    public string SummarisationPrompt { get; set; } = string.Empty;
}

public class UpdateDocumentSummarisationTemplateRequest
{
    public string? SummarisationName { get; set; }
    public string? SummarisationDescription { get; set; }
    public string? SummarisationPrompt { get; set; }
    public bool? IsActive { get; set; }
}

public class DocumentExtractionFieldDto
{
    public int DocumentExtractionFieldId { get; set; }
    public int DocumentExtractionTemplateId { get; set; }
    public string FieldName { get; set; } = string.Empty;
    public string? ExampleValue { get; set; }
    public string? AnchorTextBefore { get; set; }
    public string? AnchorTextAfter { get; set; }
    public string? FieldExtractionPrompt { get; set; }
    public int? PageNumber { get; set; }
    public string? BoundingBoxJson { get; set; }
    public bool IsActive { get; set; }
}

public class DocumentExtractionTemplateDto
{
    public int DocumentExtractionTemplateId { get; set; }
    public string ExtractionTemplateName { get; set; } = string.Empty;
    public string? ExtractionTemplateDescription { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public List<DocumentExtractionFieldDto> Fields { get; set; } = new();
}

public class CreateDocumentExtractionTemplateRequest
{
    public string ExtractionTemplateName { get; set; } = string.Empty;
    public string? ExtractionTemplateDescription { get; set; }
}

public class UpdateDocumentExtractionTemplateRequest
{
    public string? ExtractionTemplateName { get; set; }
    public string? ExtractionTemplateDescription { get; set; }
    public bool? IsActive { get; set; }
    public List<UpdateDocumentExtractionFieldRequest>? Fields { get; set; }
}

public class CreateDocumentExtractionFieldRequest
{
    public string FieldName { get; set; } = string.Empty;
    public string? ExampleValue { get; set; }
    public string? AnchorTextBefore { get; set; }
    public string? AnchorTextAfter { get; set; }
    public string? FieldExtractionPrompt { get; set; }
    public int? PageNumber { get; set; }
    public string? BoundingBoxJson { get; set; }
}

public class UpdateDocumentExtractionFieldRequest
{
    public string FieldName { get; set; } = string.Empty;
    public string? ExampleValue { get; set; }
    public string? AnchorTextBefore { get; set; }
    public string? AnchorTextAfter { get; set; }
    public string? FieldExtractionPrompt { get; set; }
    public int? PageNumber { get; set; }
    public string? BoundingBoxJson { get; set; }
    public bool IsActive { get; set; } = true;
}

public class CreateDocumentCorrectionFeedbackRequest
{
    public long DocumentProcessingRunId { get; set; }
    public string ProcessingType { get; set; } = string.Empty;
    public string? FieldName { get; set; }
    public string? OriginalValue { get; set; }
    public string? CorrectedValue { get; set; }
    public string? ReviewerNotes { get; set; }
}

public class DocumentClassificationSuggestionDto
{
    public string FileName { get; set; } = string.Empty;
    public string SuggestedLabel { get; set; } = string.Empty;
    public string SuggestedDescription { get; set; } = string.Empty;
    public string SuggestedPrompt { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
}

public class DocumentClassificationTestResponse
{
    public string FileName { get; set; } = string.Empty;
    public string ClassificationLabel { get; set; } = "Unclassified";
    public string? ClassificationDescription { get; set; }
    public double ClassificationScore { get; set; }
    public string ClassificationExplainability { get; set; } = string.Empty;
    public int? DocumentClassificationLabelId { get; set; }
    public string TextPreview { get; set; } = string.Empty;
}

public class DocumentSummarisationPreviewResponse
{
    public string FileName { get; set; } = string.Empty;
    public string PromptUsed { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
}

public class DocumentExtractionPreviewResponse
{
    public string FileName { get; set; } = string.Empty;
    public string ExtractedText { get; set; } = string.Empty;
    public string TextPreview { get; set; } = string.Empty;
    public List<DocumentExtractionSuggestedFieldDto> SuggestedFields { get; set; } = new();
    /// <summary>When preview uses saved template extraction, identifies which template ran.</summary>
    public int? ExtractionTemplateId { get; set; }
    /// <summary>"template_fields" uses saved fields (same path as workflows); "ai_suggestions" is heuristic/AI guesses.</summary>
    public string PreviewMode { get; set; } = string.Empty;
}

public class DocumentExtractionSuggestedFieldDto
{
    public string FieldName { get; set; } = string.Empty;
    public string ExampleValue { get; set; } = string.Empty;
    /// <summary>Optional: normalized token for {field:&lt;token&gt;} substitutions (same as workflows).</summary>
    public string? NormalizedToken { get; set; }
}

public class SuggestExtractionFromSelectionRequest
{
    public string SelectedText { get; set; } = string.Empty;
    public string? ExtractedText { get; set; }
}

public class TriggerPropertyHubEmailProcessingRequest
{
    public string? MailboxUser { get; set; }
    public int? MaxEmails { get; set; }
}

public class TriggerPropertyHubEmailProcessingResponse
{
    public string Status { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public object? ProcessingResult { get; set; }
}

public class DocumentWorkflowStepDto
{
    public int DocumentWorkflowStepId { get; set; }
    public int DocumentWorkflowRuleId { get; set; }
    public int StepOrder { get; set; }
    public string StepType { get; set; } = string.Empty;
    public string? StepConfigJson { get; set; }
    public bool IsActive { get; set; }
}

public class DocumentWorkflowRuleDto
{
    public int DocumentWorkflowRuleId { get; set; }
    public string WorkflowName { get; set; } = string.Empty;
    public string ClassificationLabel { get; set; } = string.Empty;
    public double MinimumScore { get; set; }
    public int Priority { get; set; }
    public bool StopOnFailure { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public List<DocumentWorkflowStepDto> Steps { get; set; } = new();
}

public class UpsertDocumentWorkflowStepRequest
{
    public int StepOrder { get; set; }
    public string StepType { get; set; } = string.Empty;
    public string? StepConfigJson { get; set; }
    public bool IsActive { get; set; } = true;
}

public class CreateDocumentWorkflowRuleRequest
{
    public string WorkflowName { get; set; } = string.Empty;
    public string ClassificationLabel { get; set; } = string.Empty;
    public double MinimumScore { get; set; } = 0.28;
    public int Priority { get; set; } = 100;
    public bool StopOnFailure { get; set; } = true;
    public List<UpsertDocumentWorkflowStepRequest> Steps { get; set; } = new();
}

public class UpdateDocumentWorkflowRuleRequest
{
    public string? WorkflowName { get; set; }
    public string? ClassificationLabel { get; set; }
    public double? MinimumScore { get; set; }
    public int? Priority { get; set; }
    public bool? StopOnFailure { get; set; }
    public bool? IsActive { get; set; }
    public List<UpsertDocumentWorkflowStepRequest>? Steps { get; set; }
}

public class DocumentWorkflowStepTestResultDto
{
    public int StepOrder { get; set; }
    public string StepType { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string Details { get; set; } = string.Empty;
}

public class DocumentWorkflowRuleTestResponse
{
    public int DocumentWorkflowRuleId { get; set; }
    public string WorkflowName { get; set; } = string.Empty;
    public string ClassificationLabel { get; set; } = string.Empty;
    public double ClassificationScore { get; set; }
    public bool RuleEligible { get; set; }
    public string EligibilityReason { get; set; } = string.Empty;
    public List<DocumentWorkflowStepTestResultDto> Steps { get; set; } = new();
}

public class DocumentWorkflowExtractionSnapshotDto
{
    public string FieldName { get; set; } = string.Empty;
    public string? FieldValue { get; set; }
    public string? Comments { get; set; }
}

public class DocumentWorkflowAuditRunDto
{
    public long DocumentWorkflowAuditRunId { get; set; }
    public string? Subject { get; set; }
    public string? ClassificationLabel { get; set; }
    public double? ClassificationScore { get; set; }
    public string Status { get; set; } = string.Empty;
    public string? ErrorMessage { get; set; }
    public DateTime StartedDate { get; set; }
    public DateTime? CompletedDate { get; set; }
    public string? SummarisationText { get; set; }
    public List<DocumentWorkflowExtractionSnapshotDto> ExtractionSnapshots { get; set; } = new();
}

public class DocumentWorkflowRuleRunHistoryResponse
{
    public int DocumentWorkflowRuleId { get; set; }
    public string WorkflowName { get; set; } = string.Empty;
    public List<DocumentWorkflowAuditRunDto> Runs { get; set; } = new();
}
