import apiClient from './api';

export interface DocumentClassificationLabelDto {
  documentClassificationLabelId: number;
  documentLabelSetId: number;
  classificationLabel: string;
  classificationDescription?: string;
  classificationPrompt: string;
  seedDocumentName?: string;
  isAutoGenerated: boolean;
  isActive: boolean;
}

export interface DocumentLabelSetDto {
  documentLabelSetId: number;
  labelSetName: string;
  labelSetDescription?: string;
  isActive: boolean;
  createdDate: string;
  labels: DocumentClassificationLabelDto[];
}

export interface CreateDocumentLabelSetRequest {
  labelSetName: string;
  labelSetDescription?: string;
}

export interface CreateDocumentClassificationLabelRequest {
  classificationLabel: string;
  classificationDescription?: string;
  classificationPrompt: string;
  seedDocumentName?: string;
  seedDocumentHash?: string;
  isAutoGenerated?: boolean;
}

export interface DocumentSummarisationTemplateDto {
  documentSummarisationTemplateId: number;
  summarisationName: string;
  summarisationDescription?: string;
  summarisationPrompt: string;
  isActive: boolean;
  createdDate: string;
}

export interface CreateDocumentSummarisationTemplateRequest {
  summarisationName: string;
  summarisationDescription?: string;
  summarisationPrompt: string;
}

export interface DocumentExtractionFieldDto {
  documentExtractionFieldId: number;
  documentExtractionTemplateId: number;
  fieldName: string;
  exampleValue?: string;
  anchorTextBefore?: string;
  anchorTextAfter?: string;
  fieldExtractionPrompt?: string;
  pageNumber?: number;
  boundingBoxJson?: string;
  isActive: boolean;
}

export interface DocumentExtractionTemplateDto {
  documentExtractionTemplateId: number;
  extractionTemplateName: string;
  extractionTemplateDescription?: string;
  isActive: boolean;
  createdDate: string;
  fields: DocumentExtractionFieldDto[];
}

export interface CreateDocumentExtractionTemplateRequest {
  extractionTemplateName: string;
  extractionTemplateDescription?: string;
}

export interface CreateDocumentExtractionFieldRequest {
  fieldName: string;
  exampleValue?: string;
  anchorTextBefore?: string;
  anchorTextAfter?: string;
  fieldExtractionPrompt?: string;
  pageNumber?: number;
  boundingBoxJson?: string;
}

export interface DocumentClassificationSuggestionDto {
  fileName: string;
  suggestedLabel: string;
  suggestedDescription: string;
  suggestedPrompt: string;
  textPreview: string;
}

export interface DocumentSummarisationPreviewResponse {
  fileName: string;
  promptUsed: string;
  summary: string;
  textPreview: string;
}

export interface DocumentExtractionPreviewResponse {
  fileName: string;
  extractedText: string;
  textPreview: string;
}

export const documentHubService = {
  getLabelSets: async (): Promise<DocumentLabelSetDto[]> => {
    return await apiClient<DocumentLabelSetDto[]>('/document-hub/label-sets');
  },

  createLabelSet: async (request: CreateDocumentLabelSetRequest): Promise<DocumentLabelSetDto> => {
    return await apiClient<DocumentLabelSetDto>('/document-hub/label-sets', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  },

  createClassificationLabel: async (
    labelSetId: number,
    request: CreateDocumentClassificationLabelRequest
  ): Promise<DocumentClassificationLabelDto> => {
    return await apiClient<DocumentClassificationLabelDto>(`/document-hub/label-sets/${labelSetId}/labels`, {
      method: 'POST',
      body: JSON.stringify(request),
    });
  },

  getSummarisationTemplates: async (): Promise<DocumentSummarisationTemplateDto[]> => {
    return await apiClient<DocumentSummarisationTemplateDto[]>('/document-hub/summarisation-templates');
  },

  createSummarisationTemplate: async (
    request: CreateDocumentSummarisationTemplateRequest
  ): Promise<DocumentSummarisationTemplateDto> => {
    return await apiClient<DocumentSummarisationTemplateDto>('/document-hub/summarisation-templates', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  },

  getExtractionTemplates: async (): Promise<DocumentExtractionTemplateDto[]> => {
    return await apiClient<DocumentExtractionTemplateDto[]>('/document-hub/extraction-templates');
  },

  createExtractionTemplate: async (
    request: CreateDocumentExtractionTemplateRequest
  ): Promise<DocumentExtractionTemplateDto> => {
    return await apiClient<DocumentExtractionTemplateDto>('/document-hub/extraction-templates', {
      method: 'POST',
      body: JSON.stringify(request),
    });
  },

  createExtractionField: async (
    templateId: number,
    request: CreateDocumentExtractionFieldRequest
  ): Promise<DocumentExtractionFieldDto> => {
    return await apiClient<DocumentExtractionFieldDto>(`/document-hub/extraction-templates/${templateId}/fields`, {
      method: 'POST',
      body: JSON.stringify(request),
    });
  },

  suggestClassificationLabels: async (files: File[]): Promise<DocumentClassificationSuggestionDto[]> => {
    const formData = new FormData();
    files.forEach((file) => formData.append('files', file));

    return await apiClient<DocumentClassificationSuggestionDto[]>('/document-hub/classification/suggest', {
      method: 'POST',
      body: formData,
    });
  },

  previewSummarisation: async (file: File, prompt: string): Promise<DocumentSummarisationPreviewResponse> => {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('prompt', prompt);

    return await apiClient<DocumentSummarisationPreviewResponse>('/document-hub/summarisation/preview', {
      method: 'POST',
      body: formData,
    });
  },

  previewExtraction: async (file: File): Promise<DocumentExtractionPreviewResponse> => {
    const formData = new FormData();
    formData.append('file', file);

    return await apiClient<DocumentExtractionPreviewResponse>('/document-hub/extraction/preview', {
      method: 'POST',
      body: formData,
    });
  },
};
