using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace backend.Models;

[Table("tbldocumentlabelset")]
public class DocumentLabelSet
{
    [Key]
    [Column("DocumentLabelSetId")]
    public int DocumentLabelSetId { get; set; }

    [Column("LabelSetName")]
    [MaxLength(200)]
    public string LabelSetName { get; set; } = string.Empty;

    [Column("LabelSetDescription")]
    [MaxLength(2000)]
    public string? LabelSetDescription { get; set; }

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<DocumentClassificationLabel> ClassificationLabels { get; set; } = new List<DocumentClassificationLabel>();
}

[Table("tbldocumentclassificationlabel")]
public class DocumentClassificationLabel
{
    [Key]
    [Column("DocumentClassificationLabelId")]
    public int DocumentClassificationLabelId { get; set; }

    [Column("DocumentLabelSetId")]
    public int DocumentLabelSetId { get; set; }

    [Column("ClassificationLabel")]
    [MaxLength(80)]
    public string ClassificationLabel { get; set; } = string.Empty;

    [Column("ClassificationDescription")]
    [MaxLength(2000)]
    public string? ClassificationDescription { get; set; }

    [Column("ClassificationPrompt")]
    public string ClassificationPrompt { get; set; } = string.Empty;

    [Column("SeedDocumentName")]
    [MaxLength(260)]
    public string? SeedDocumentName { get; set; }

    [Column("SeedDocumentHash")]
    [MaxLength(128)]
    public string? SeedDocumentHash { get; set; }

    [Column("IsAutoGenerated")]
    public bool IsAutoGenerated { get; set; } = true;

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    [ForeignKey(nameof(DocumentLabelSetId))]
    public virtual DocumentLabelSet? DocumentLabelSet { get; set; }
}

[Table("tbldocumentsummarisationtemplate")]
public class DocumentSummarisationTemplate
{
    [Key]
    [Column("DocumentSummarisationTemplateId")]
    public int DocumentSummarisationTemplateId { get; set; }

    [Column("SummarisationName")]
    [MaxLength(200)]
    public string SummarisationName { get; set; } = string.Empty;

    [Column("SummarisationDescription")]
    [MaxLength(2000)]
    public string? SummarisationDescription { get; set; }

    [Column("SummarisationPrompt")]
    public string SummarisationPrompt { get; set; } = string.Empty;

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }
}

[Table("tbldocumentextractiontemplate")]
public class DocumentExtractionTemplate
{
    [Key]
    [Column("DocumentExtractionTemplateId")]
    public int DocumentExtractionTemplateId { get; set; }

    [Column("ExtractionTemplateName")]
    [MaxLength(200)]
    public string ExtractionTemplateName { get; set; } = string.Empty;

    [Column("ExtractionTemplateDescription")]
    [MaxLength(2000)]
    public string? ExtractionTemplateDescription { get; set; }

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<DocumentExtractionField> ExtractionFields { get; set; } = new List<DocumentExtractionField>();
}

[Table("tbldocumentextractionfield")]
public class DocumentExtractionField
{
    [Key]
    [Column("DocumentExtractionFieldId")]
    public int DocumentExtractionFieldId { get; set; }

    [Column("DocumentExtractionTemplateId")]
    public int DocumentExtractionTemplateId { get; set; }

    [Column("FieldName")]
    [MaxLength(200)]
    public string FieldName { get; set; } = string.Empty;

    [Column("ExampleValue")]
    [MaxLength(2000)]
    public string? ExampleValue { get; set; }

    [Column("AnchorTextBefore")]
    [MaxLength(1000)]
    public string? AnchorTextBefore { get; set; }

    [Column("AnchorTextAfter")]
    [MaxLength(1000)]
    public string? AnchorTextAfter { get; set; }

    [Column("FieldExtractionPrompt")]
    public string? FieldExtractionPrompt { get; set; }

    [Column("PageNumber")]
    public int? PageNumber { get; set; }

    [Column("BoundingBoxJson")]
    public string? BoundingBoxJson { get; set; }

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    [ForeignKey(nameof(DocumentExtractionTemplateId))]
    public virtual DocumentExtractionTemplate? DocumentExtractionTemplate { get; set; }
}

[Table("tbldocumentcorrectionfeedback")]
public class DocumentCorrectionFeedback
{
    [Key]
    [Column("DocumentCorrectionFeedbackId")]
    public long DocumentCorrectionFeedbackId { get; set; }

    [Column("DocumentProcessingRunId")]
    public long DocumentProcessingRunId { get; set; }

    [Column("ProcessingType")]
    [MaxLength(50)]
    public string ProcessingType { get; set; } = string.Empty;

    [Column("FieldName")]
    [MaxLength(200)]
    public string? FieldName { get; set; }

    [Column("OriginalValue")]
    public string? OriginalValue { get; set; }

    [Column("CorrectedValue")]
    public string? CorrectedValue { get; set; }

    [Column("ReviewerNotes")]
    [MaxLength(2000)]
    public string? ReviewerNotes { get; set; }

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
}

[Table("tbldocumentworkflowrule")]
public class DocumentWorkflowRule
{
    [Key]
    [Column("DocumentWorkflowRuleId")]
    public int DocumentWorkflowRuleId { get; set; }

    [Column("WorkflowName")]
    [MaxLength(200)]
    public string WorkflowName { get; set; } = string.Empty;

    [Column("ClassificationLabel")]
    [MaxLength(120)]
    public string ClassificationLabel { get; set; } = string.Empty;

    [Column("MinimumScore")]
    public double MinimumScore { get; set; } = 0.28;

    [Column("Priority")]
    public int Priority { get; set; } = 100;

    [Column("StopOnFailure")]
    public bool StopOnFailure { get; set; } = true;

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<DocumentWorkflowStep> Steps { get; set; } = new List<DocumentWorkflowStep>();
}

[Table("tbldocumentworkflowstep")]
public class DocumentWorkflowStep
{
    [Key]
    [Column("DocumentWorkflowStepId")]
    public int DocumentWorkflowStepId { get; set; }

    [Column("DocumentWorkflowRuleId")]
    public int DocumentWorkflowRuleId { get; set; }

    [Column("StepOrder")]
    public int StepOrder { get; set; }

    [Column("StepType")]
    [MaxLength(80)]
    public string StepType { get; set; } = string.Empty;

    [Column("StepConfigJson")]
    public string? StepConfigJson { get; set; }

    [Column("IsActive")]
    public bool IsActive { get; set; } = true;

    [Column("CreatedByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("CreatedDate")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    [Column("UpdatedByUserId")]
    public int? UpdatedByUserId { get; set; }

    [Column("UpdatedDate")]
    public DateTime? UpdatedDate { get; set; }

    [ForeignKey(nameof(DocumentWorkflowRuleId))]
    public virtual DocumentWorkflowRule? Rule { get; set; }
}
